/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiDietCard: typeof import('./src/components/diet/AiDietCard.vue')['default']
    AIDietTipIcon: typeof import('./src/components/AIDietTipIcon.vue')['default']
    CommentList: typeof import('./src/components/diet/CommentList.vue')['default']
    DietCard: typeof import('./src/components/diet/DietCard.vue')['default']
    EmptyData: typeof import('./src/components/emptyData.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LanguageSwitcher: typeof import('./src/components/LanguageSwitcher.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideTabList: typeof import('./src/components/diet/SideTabList.vue')['default']
    TabBar: typeof import('./src/components/TabBar.vue')['default']
    TabList: typeof import('./src/components/diet/TabList.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TipIcon: typeof import('./src/components/TipIcon.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCollapse: typeof import('vant/es')['Collapse']
    VanCollapseItem: typeof import('vant/es')['CollapseItem']
    VanDropdownItem: typeof import('vant/es')['DropdownItem']
    VanDropdownMenu: typeof import('vant/es')['DropdownMenu']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanSearch: typeof import('vant/es')['Search']
    VanSidebar: typeof import('vant/es')['Sidebar']
    VanSidebarItem: typeof import('vant/es')['SidebarItem']
    VanSticky: typeof import('vant/es')['Sticky']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
    VideoCard: typeof import('./src/components/guide/VideoCard.vue')['default']
    VideoList: typeof import('./src/components/guide/VideoList.vue')['default']
    VideoPlayerBox: typeof import('./src/components/guide/VideoPlayerBox.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
